PO-64: add Label type.
openmotics/typescript-types pull request #24
Opened 2020-10-13 06:58 UTC by mremil6

2020-10-23 07:55 UTC, iOlivier approved these changes

2020-10-23 08:05 UTC, itolegmysin commented on src/label/label.d.ts
> +    label_id: number;
We using underscore only for API responses:
```
LabelApi {
  ...
  label_id: number
} 
```
and
```
Label {
  ...
  labelId: number;
}
```

2020-10-23 08:05 UTC, itolegmysin commented on src/label/label.d.ts
> +    label_type: string;
see above

2020-10-29 16:00 UTC, iOlivier requested changes
See above

2021-01-15 10:55 UTC, iOlivier approved these changes

2021-01-15 10:59 UTC, merged